version: "3.7"

services:
  saltmaster:
    build:
      context: .
      dockerfile: saltmaster.dockerfile
  saltminion:
    build:
      context: .
      dockerfile: saltminion.dockerfile
    depends_on:
      - saltmaster
